### ISSUE TITLE
Regression: Allow access from Objective-C

### ISSUE THREAD

**Issue by michaeleustace** [carloe/LicenseGenerator-iOS#18]
I have a mixed Objective-C and Swift project using LicensesViewController which I have just updated to Swift 4 from Swift 3

However this does now not compile because Objective-C code cannot see `open func loadPlist(_ bundle: Bundle, resourceName: String)`.  Swift 4 requires explicitly declaring `@objc` to functions which are exposed to Objective-C.

Could you please add `@objc` to the functions you wish to expose to Objective-C.

**Comment by carloe** [comment]
@michaeleustace should should be fixed with the `0.6.5` version I just pushed. If you are still having issues please let me know.
