### ISSUE TITLE
IPhone X support

### ISSUE THREAD

**Issue by nyekimov** [carloe/LicenseGenerator-iOS#19]
Default implementation of the `LicensesViewController` doesn't respect safe area of the view and when you scroll through data it overlaps interactive controls at the very bottom of the screen. I believe the `updateViewConstraints()` needs to be updated per ios 11.

**Comment by carloe** [comment]
@nyekimov Thanks for this. 

Could you elaborate on what kind of controls you are talking about / what your usecase is? From what I can see the `LicensesViewController` is working correctly when it's embedded in a `UITabBarController`. It also seems to have the correct content offsets when used in a `UINavigationController`.

**Comment by nyekimov** [comment]
The ` interactive controls at the very bottom of the screen` is apple terminology from https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x/.

Attaching a screenshot on which text overlaps very bottom interactive controls. If I scroll till end table view bottom inset is in place. However text overlapping at scrolling isn't correct behavior. Since ios 9 layout guides should be used with constraints. In iOS 11 apple introduces safe area which works perfectly if layout guides are in place. 

Pushed a PR with a possible fix, please take a look.
![simulator screen shot - iphone x - 2018-01-19 at 09 56 49](https://user-images.githubusercontent.com/1243986/35159444-de45259e-fcff-11e7-8c63-bde490cc013f.png)

**Comment by nyekimov** [comment]
actually checked another table views and usually content overlaps bottom controls. It's a normal behavior for table view cells. The behavior can be changed manually if developer wishes when developer has access to the view controller. Here is an issue that developer can't customize `LicensesViewController`.
Any suggestions?
Issue probably can be closed.

**Comment by carloe** [comment]
Thank you for clarifying! 

I checked the docs you linked & looked at safari as reference, and I think the layout is behaving as it should. In portrait it matches what safari does, and in landscape it does take the safe zones into account. I believe they are talking about `UITabBar`, `UIButton`, `UIToolbar`, etc when they are talking about 'interactive controls' here.

Please let me know if you still disagree. Screenshots for reference:

![group 2](https://user-images.githubusercontent.com/299107/35167618-7c922160-fd56-11e7-87da-40fa584f2f3e.png)

**Comment by carloe** [comment]
Good point... The `tableView` property of `LicensesViewController` should probably be `open`. Then you should be able do what you are trying to do. What do you think?

**Comment by nyekimov** [comment]
@carloe yeah this should probably help.

**Comment by carloe** [comment]
@nyekimov ok, I will push that change with `0.6.5` as soon as the PR #21 build passes. Thanks again for the feedback!
