### ISSUE TITLE
Ordering of licenses?

### ISSUE THREAD

**Issue by crspybits** [carloe/LicenseGenerator-iOS#28]
Hey, I really like this :). It lets me include licenses for both code libraries and graphics assets. I've got it working in a production app from my last job! One thing I wonder about though-- what defines the ordering of licenses in the Settings bundle? e.g., in this 

![](https://github.com/carloe/LicenseGenerator-iOS/blob/master/screenshot.png)

SwiftyJSON comes before Alamofire in the list not after as I might expect.

Would you be open to a PR that enables some different sort order? E.g., alphabetic?

Thanks,
Chris.

**Comment by crspybits** [comment]
Or, looking again it looks like you've fixed this! :).

**Comment by carloe** [comment]
I don't think I changed anything that would have fixed the behavior. The script just goes by whatever order `os.walk()` returns. Glad it is now working for you tho!
