### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by george-gymamigo** [carloe/LicenseGenerator-iOS#30]
Upon running I get the following build  error:

/Users/georgedendle/Library/Developer/Xcode/DerivedData/GYM_AMIGO-czcrxvthuppywdaoiqdvgzsunpsy/Build/Intermediates.noindex/GYM AMIGO.build/Debug-iphoneos/GYM AMIGO.build/Script-FDFA256422CBC3C30037637F.sh: line 2: ./credits.py: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

This is my run script code
./credits.py -s "$SRCROOT" -o "$SRCROOT/Project/Settings.bundle/Credits.plist"

**Comment by carloe** [comment]
@george-gymamigo this looks like the path to `credits.py` in the build phase is wrong. Where did you put the script relative to your xcode project file (i.e your `.xcworkspace`)?
