### ISSUE TITLE
Can you please clarify what you mean by "make sure the resulting plist is included in the app target"?

### ISSUE THREAD

**Issue by sarbogast** [carloe/LicenseGenerator-iOS#31]
Nothing appears in the LicensesViewController, and it seems like Credits.plist cannot be loaded properly.
I suspect it's because I didn't do anything in particular to include Credits.plist in the target. Settings.bundle has the target box checked in Target Membership inspector, but there is no checkbox for Root.plist or Credits.plist under it.
So can you please clarify what you mean by "make sure the resulting plist is included in the app target"?

**Comment by sarbogast** [comment]
It's ok, I think I figured it out. Based on the example project, I saw that you didn't generate Credits.plist in the Settings.bundle but at the root of the project. When I did the same and added Credits.plist to the project target, it worked. Not sure if we can also load the plist from the Settings.bundle in LicensesViewController, but I don't need Settings.bundle anyway so that's fine.

**Comment by george-gymamigo** [comment]
@sarbogast how did you managed to fix this, as like you I'm not using settings.bundle, I've created a Credits.plist but when running the acknowledgement vc is empty?! Thanks
