### ISSUE TITLE
Font is black on black when using dark mode in iOS 13

### ISSUE THREAD

**Issue by Schaefers** [carloe/LicenseGenerator-iOS#33]
### Description

The font color is not properly set for iOS 13. As a result it is shown black on black when using the system dark mode.

![IMG_1427](https://user-images.githubusercontent.com/9284160/68294194-df9aaa00-008f-11ea-8b84-e6661d0c3d3e.jpeg)

**Comment by carloe** [comment]
This is fixed in release `0.8.0` :party
