### ISSUE TITLE
No python in macOS 12.3

### ISSUE THREAD

**Issue by Urkman** [carloe/LicenseGenerator-iOS#40]
As there is no python in macOS 12.3 the current script is not working.
Any ideas how to fix this,  beside installing our own python 2.x and changing the path?

**Comment by rbarthomeuf** [comment]
I have the same issue. If I install Python with brew, I get Python 3.
It's not compatible with this Pod.
Does anyone as a good solution ?

**Comment by carloe** [comment]
@rbarthomeuf I just pushed version `0.10.0`, which migrates the script to Python 3. Please let me know if you are still having issues with this version.

**Comment by rbarthomeuf** [comment]
> @rbarthomeuf I just pushed version `0.10.0`, which migrates the script to Python 3. Please let me know if you are still having issues with this version.

Great! It works perfectly ! 
Thanks for your quick fix !
