### ISSUE TITLE
Cant run on MacOS Ventura 13.0.1

### ISSUE THREAD

**Issue by nemanja-nisic** [carloe/LicenseGenerator-iOS#41]
When I try to build the app I get:

credits.py: /usr/bin/python: bad interpreter: No such file or directory

I've installed python but due to system integration protection or something I cannot link it to /usr/bin/python.
Do you know of any fix for this?

Thanks

**Comment by nemanja-nisic** [comment]
Still getting same error. Do I need to do something on my side?

**Comment by carloe** [comment]
@nemanja-nisic that is odd. Nothing in the script should be pointing explicitly to `/usr/bin/python`. 

Did you re-copy `credits.py` manually after you updated to 0.11.0 (cocoapods wont update the script)? 

What method did you use to install python on your system? And what do you get when you type `which python3` in the terminal?

**Comment by nemanja-nisic** [comment]
@carloe 
My apologies, I forgot to copy credits.py again after update.

Works great now, thank you very much! Great library ( POD! ).

**Comment by carloe** [comment]
Awesome! Glad it worked out!
